/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { IDepositable } from "../IDepositable";

export class IDepositable__factory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IDepositable {
    return new Contract(address, _abi, signerOrProvider) as IDepositable;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "releaseTime_",
        type: "uint256",
      },
      {
        internalType: "string",
        name: "comment_",
        type: "string",
      },
    ],
    name: "deposit",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
];
