"use strict";
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
Object.defineProperty(exports, "__esModule", { value: true });
exports.IDepositable__factory = void 0;
const ethers_1 = require("ethers");
class IDepositable__factory {
    static connect(address, signerOrProvider) {
        return new ethers_1.Contract(address, _abi, signerOrProvider);
    }
}
exports.IDepositable__factory = IDepositable__factory;
const _abi = [
    {
        inputs: [
            {
                internalType: "uint256",
                name: "releaseTime_",
                type: "uint256",
            },
            {
                internalType: "string",
                name: "comment_",
                type: "string",
            },
        ],
        name: "deposit",
        outputs: [],
        stateMutability: "payable",
        type: "function",
    },
];
//# sourceMappingURL=IDepositable__factory.js.map