/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface ISeedInterface extends ethers.utils.Interface {
  functions: {
    "afid()": FunctionFragment;
    "consume()": FunctionFragment;
    "consumed()": FunctionFragment;
    "dislikes()": FunctionFragment;
    "likes()": FunctionFragment;
    "submitter()": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "afid", values?: undefined): string;
  encodeFunctionData(functionFragment: "consume", values?: undefined): string;
  encodeFunctionData(functionFragment: "consumed", values?: undefined): string;
  encodeFunctionData(functionFragment: "dislikes", values?: undefined): string;
  encodeFunctionData(functionFragment: "likes", values?: undefined): string;
  encodeFunctionData(functionFragment: "submitter", values?: undefined): string;

  decodeFunctionResult(functionFragment: "afid", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "consume", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "consumed", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "dislikes", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "likes", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "submitter", data: BytesLike): Result;

  events: {};
}

export class ISeed extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: ISeedInterface;

  functions: {
    afid(overrides?: CallOverrides): Promise<[string]>;

    "afid()"(overrides?: CallOverrides): Promise<[string]>;

    consume(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "consume()"(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    consumed(overrides?: CallOverrides): Promise<[boolean]>;

    "consumed()"(overrides?: CallOverrides): Promise<[boolean]>;

    dislikes(overrides?: CallOverrides): Promise<[BigNumber]>;

    "dislikes()"(overrides?: CallOverrides): Promise<[BigNumber]>;

    likes(overrides?: CallOverrides): Promise<[BigNumber]>;

    "likes()"(overrides?: CallOverrides): Promise<[BigNumber]>;

    submitter(overrides?: CallOverrides): Promise<[string]>;

    "submitter()"(overrides?: CallOverrides): Promise<[string]>;
  };

  afid(overrides?: CallOverrides): Promise<string>;

  "afid()"(overrides?: CallOverrides): Promise<string>;

  consume(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "consume()"(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  consumed(overrides?: CallOverrides): Promise<boolean>;

  "consumed()"(overrides?: CallOverrides): Promise<boolean>;

  dislikes(overrides?: CallOverrides): Promise<BigNumber>;

  "dislikes()"(overrides?: CallOverrides): Promise<BigNumber>;

  likes(overrides?: CallOverrides): Promise<BigNumber>;

  "likes()"(overrides?: CallOverrides): Promise<BigNumber>;

  submitter(overrides?: CallOverrides): Promise<string>;

  "submitter()"(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    afid(overrides?: CallOverrides): Promise<string>;

    "afid()"(overrides?: CallOverrides): Promise<string>;

    consume(overrides?: CallOverrides): Promise<void>;

    "consume()"(overrides?: CallOverrides): Promise<void>;

    consumed(overrides?: CallOverrides): Promise<boolean>;

    "consumed()"(overrides?: CallOverrides): Promise<boolean>;

    dislikes(overrides?: CallOverrides): Promise<BigNumber>;

    "dislikes()"(overrides?: CallOverrides): Promise<BigNumber>;

    likes(overrides?: CallOverrides): Promise<BigNumber>;

    "likes()"(overrides?: CallOverrides): Promise<BigNumber>;

    submitter(overrides?: CallOverrides): Promise<string>;

    "submitter()"(overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    afid(overrides?: CallOverrides): Promise<BigNumber>;

    "afid()"(overrides?: CallOverrides): Promise<BigNumber>;

    consume(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "consume()"(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    consumed(overrides?: CallOverrides): Promise<BigNumber>;

    "consumed()"(overrides?: CallOverrides): Promise<BigNumber>;

    dislikes(overrides?: CallOverrides): Promise<BigNumber>;

    "dislikes()"(overrides?: CallOverrides): Promise<BigNumber>;

    likes(overrides?: CallOverrides): Promise<BigNumber>;

    "likes()"(overrides?: CallOverrides): Promise<BigNumber>;

    submitter(overrides?: CallOverrides): Promise<BigNumber>;

    "submitter()"(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    afid(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "afid()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    consume(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "consume()"(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    consumed(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "consumed()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    dislikes(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "dislikes()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    likes(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "likes()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    submitter(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "submitter()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
