/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  Contract,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface TurboFilInterface extends ethers.utils.Interface {
  functions: {
    "DEFAULT_ADMIN_ROLE()": FunctionFragment;
    "REGISTER_ROLE()": FunctionFragment;
    "REWARD_ROLE()": FunctionFragment;
    "SEED_ROLE()": FunctionFragment;
    "SUBMIT_ROLE()": FunctionFragment;
    "VERIFY_ROLE()": FunctionFragment;
    "distributeTFC()": FunctionFragment;
    "getRoleAdmin(bytes32)": FunctionFragment;
    "grantRole(bytes32,address)": FunctionFragment;
    "hasRole(bytes32,address)": FunctionFragment;
    "initialize(address,address,address,address)": FunctionFragment;
    "registerRNode(address,string)": FunctionFragment;
    "renounceRole(bytes32,address)": FunctionFragment;
    "revokeRole(bytes32,address)": FunctionFragment;
    "submitSector(address,address,string,string)": FunctionFragment;
    "submitSeed(address,string)": FunctionFragment;
    "supportsInterface(bytes4)": FunctionFragment;
    "verifySector(address,address,bool)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "REGISTER_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "REWARD_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "SEED_ROLE", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "SUBMIT_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "VERIFY_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "distributeTFC",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [string, string, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "registerRNode",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "submitSector",
    values: [string, string, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "submitSeed",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verifySector",
    values: [string, string, boolean]
  ): string;

  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "REGISTER_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "REWARD_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "SEED_ROLE", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "SUBMIT_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "VERIFY_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "distributeTFC",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerRNode",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "submitSector",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "submitSeed", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifySector",
    data: BytesLike
  ): Result;

  events: {
    "RegisterRNode(address,address,string)": EventFragment;
    "RoleAdminChanged(bytes32,bytes32,bytes32)": EventFragment;
    "RoleGranted(bytes32,address,address)": EventFragment;
    "RoleRevoked(bytes32,address,address)": EventFragment;
    "SubmitSector(address,address,string)": EventFragment;
    "SubmitSeed(address,address,string)": EventFragment;
    "VerifySector(address,address,bool)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "RegisterRNode"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RoleAdminChanged"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RoleGranted"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RoleRevoked"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SubmitSector"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SubmitSeed"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "VerifySector"): EventFragment;
}

export class TurboFil extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: TurboFilInterface;

  functions: {
    DEFAULT_ADMIN_ROLE(overrides?: CallOverrides): Promise<[string]>;

    "DEFAULT_ADMIN_ROLE()"(overrides?: CallOverrides): Promise<[string]>;

    REGISTER_ROLE(overrides?: CallOverrides): Promise<[string]>;

    "REGISTER_ROLE()"(overrides?: CallOverrides): Promise<[string]>;

    REWARD_ROLE(overrides?: CallOverrides): Promise<[string]>;

    "REWARD_ROLE()"(overrides?: CallOverrides): Promise<[string]>;

    SEED_ROLE(overrides?: CallOverrides): Promise<[string]>;

    "SEED_ROLE()"(overrides?: CallOverrides): Promise<[string]>;

    SUBMIT_ROLE(overrides?: CallOverrides): Promise<[string]>;

    "SUBMIT_ROLE()"(overrides?: CallOverrides): Promise<[string]>;

    VERIFY_ROLE(overrides?: CallOverrides): Promise<[string]>;

    "VERIFY_ROLE()"(overrides?: CallOverrides): Promise<[string]>;

    distributeTFC(
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "distributeTFC()"(
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    getRoleAdmin(role: BytesLike, overrides?: CallOverrides): Promise<[string]>;

    "getRoleAdmin(bytes32)"(
      role: BytesLike,
      overrides?: CallOverrides
    ): Promise<[string]>;

    grantRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "grantRole(bytes32,address)"(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    hasRole(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    "hasRole(bytes32,address)"(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    initialize(
      sectorSubmissionShare_: string,
      sectorVerificationShare_: string,
      seedSubmissionShare_: string,
      seedEvaluationShare_: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "initialize(address,address,address,address)"(
      sectorSubmissionShare_: string,
      sectorVerificationShare_: string,
      seedSubmissionShare_: string,
      seedEvaluationShare_: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    registerRNode(
      owner_: string,
      afid_: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "registerRNode(address,string)"(
      owner_: string,
      afid_: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    renounceRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "renounceRole(bytes32,address)"(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    revokeRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "revokeRole(bytes32,address)"(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    submitSector(
      rnode_: string,
      submitter_: string,
      afid_: string,
      merkleRoot_: string,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "submitSector(address,address,string,string)"(
      rnode_: string,
      submitter_: string,
      afid_: string,
      merkleRoot_: string,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    submitSeed(
      submitter_: string,
      afid_: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "submitSeed(address,string)"(
      submitter_: string,
      afid_: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    supportsInterface(
      interfaceId: BytesLike,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    "supportsInterface(bytes4)"(
      interfaceId: BytesLike,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    verifySector(
      sector_: string,
      seed_: string,
      success_: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "verifySector(address,address,bool)"(
      sector_: string,
      seed_: string,
      success_: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  DEFAULT_ADMIN_ROLE(overrides?: CallOverrides): Promise<string>;

  "DEFAULT_ADMIN_ROLE()"(overrides?: CallOverrides): Promise<string>;

  REGISTER_ROLE(overrides?: CallOverrides): Promise<string>;

  "REGISTER_ROLE()"(overrides?: CallOverrides): Promise<string>;

  REWARD_ROLE(overrides?: CallOverrides): Promise<string>;

  "REWARD_ROLE()"(overrides?: CallOverrides): Promise<string>;

  SEED_ROLE(overrides?: CallOverrides): Promise<string>;

  "SEED_ROLE()"(overrides?: CallOverrides): Promise<string>;

  SUBMIT_ROLE(overrides?: CallOverrides): Promise<string>;

  "SUBMIT_ROLE()"(overrides?: CallOverrides): Promise<string>;

  VERIFY_ROLE(overrides?: CallOverrides): Promise<string>;

  "VERIFY_ROLE()"(overrides?: CallOverrides): Promise<string>;

  distributeTFC(
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "distributeTFC()"(
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  getRoleAdmin(role: BytesLike, overrides?: CallOverrides): Promise<string>;

  "getRoleAdmin(bytes32)"(
    role: BytesLike,
    overrides?: CallOverrides
  ): Promise<string>;

  grantRole(
    role: BytesLike,
    account: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "grantRole(bytes32,address)"(
    role: BytesLike,
    account: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  hasRole(
    role: BytesLike,
    account: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  "hasRole(bytes32,address)"(
    role: BytesLike,
    account: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  initialize(
    sectorSubmissionShare_: string,
    sectorVerificationShare_: string,
    seedSubmissionShare_: string,
    seedEvaluationShare_: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "initialize(address,address,address,address)"(
    sectorSubmissionShare_: string,
    sectorVerificationShare_: string,
    seedSubmissionShare_: string,
    seedEvaluationShare_: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  registerRNode(
    owner_: string,
    afid_: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "registerRNode(address,string)"(
    owner_: string,
    afid_: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  renounceRole(
    role: BytesLike,
    account: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "renounceRole(bytes32,address)"(
    role: BytesLike,
    account: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  revokeRole(
    role: BytesLike,
    account: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "revokeRole(bytes32,address)"(
    role: BytesLike,
    account: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  submitSector(
    rnode_: string,
    submitter_: string,
    afid_: string,
    merkleRoot_: string,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "submitSector(address,address,string,string)"(
    rnode_: string,
    submitter_: string,
    afid_: string,
    merkleRoot_: string,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  submitSeed(
    submitter_: string,
    afid_: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "submitSeed(address,string)"(
    submitter_: string,
    afid_: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  supportsInterface(
    interfaceId: BytesLike,
    overrides?: CallOverrides
  ): Promise<boolean>;

  "supportsInterface(bytes4)"(
    interfaceId: BytesLike,
    overrides?: CallOverrides
  ): Promise<boolean>;

  verifySector(
    sector_: string,
    seed_: string,
    success_: boolean,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "verifySector(address,address,bool)"(
    sector_: string,
    seed_: string,
    success_: boolean,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    DEFAULT_ADMIN_ROLE(overrides?: CallOverrides): Promise<string>;

    "DEFAULT_ADMIN_ROLE()"(overrides?: CallOverrides): Promise<string>;

    REGISTER_ROLE(overrides?: CallOverrides): Promise<string>;

    "REGISTER_ROLE()"(overrides?: CallOverrides): Promise<string>;

    REWARD_ROLE(overrides?: CallOverrides): Promise<string>;

    "REWARD_ROLE()"(overrides?: CallOverrides): Promise<string>;

    SEED_ROLE(overrides?: CallOverrides): Promise<string>;

    "SEED_ROLE()"(overrides?: CallOverrides): Promise<string>;

    SUBMIT_ROLE(overrides?: CallOverrides): Promise<string>;

    "SUBMIT_ROLE()"(overrides?: CallOverrides): Promise<string>;

    VERIFY_ROLE(overrides?: CallOverrides): Promise<string>;

    "VERIFY_ROLE()"(overrides?: CallOverrides): Promise<string>;

    distributeTFC(overrides?: CallOverrides): Promise<void>;

    "distributeTFC()"(overrides?: CallOverrides): Promise<void>;

    getRoleAdmin(role: BytesLike, overrides?: CallOverrides): Promise<string>;

    "getRoleAdmin(bytes32)"(
      role: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    grantRole(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "grantRole(bytes32,address)"(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<void>;

    hasRole(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    "hasRole(bytes32,address)"(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    initialize(
      sectorSubmissionShare_: string,
      sectorVerificationShare_: string,
      seedSubmissionShare_: string,
      seedEvaluationShare_: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "initialize(address,address,address,address)"(
      sectorSubmissionShare_: string,
      sectorVerificationShare_: string,
      seedSubmissionShare_: string,
      seedEvaluationShare_: string,
      overrides?: CallOverrides
    ): Promise<void>;

    registerRNode(
      owner_: string,
      afid_: string,
      overrides?: CallOverrides
    ): Promise<string>;

    "registerRNode(address,string)"(
      owner_: string,
      afid_: string,
      overrides?: CallOverrides
    ): Promise<string>;

    renounceRole(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "renounceRole(bytes32,address)"(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<void>;

    revokeRole(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "revokeRole(bytes32,address)"(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<void>;

    submitSector(
      rnode_: string,
      submitter_: string,
      afid_: string,
      merkleRoot_: string,
      overrides?: CallOverrides
    ): Promise<string>;

    "submitSector(address,address,string,string)"(
      rnode_: string,
      submitter_: string,
      afid_: string,
      merkleRoot_: string,
      overrides?: CallOverrides
    ): Promise<string>;

    submitSeed(
      submitter_: string,
      afid_: string,
      overrides?: CallOverrides
    ): Promise<string>;

    "submitSeed(address,string)"(
      submitter_: string,
      afid_: string,
      overrides?: CallOverrides
    ): Promise<string>;

    supportsInterface(
      interfaceId: BytesLike,
      overrides?: CallOverrides
    ): Promise<boolean>;

    "supportsInterface(bytes4)"(
      interfaceId: BytesLike,
      overrides?: CallOverrides
    ): Promise<boolean>;

    verifySector(
      sector_: string,
      seed_: string,
      success_: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    "verifySector(address,address,bool)"(
      sector_: string,
      seed_: string,
      success_: boolean,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    RegisterRNode(
      owner: null,
      rnode: null,
      afid: null
    ): TypedEventFilter<
      [string, string, string],
      { owner: string; rnode: string; afid: string }
    >;

    RoleAdminChanged(
      role: BytesLike | null,
      previousAdminRole: BytesLike | null,
      newAdminRole: BytesLike | null
    ): TypedEventFilter<
      [string, string, string],
      { role: string; previousAdminRole: string; newAdminRole: string }
    >;

    RoleGranted(
      role: BytesLike | null,
      account: string | null,
      sender: string | null
    ): TypedEventFilter<
      [string, string, string],
      { role: string; account: string; sender: string }
    >;

    RoleRevoked(
      role: BytesLike | null,
      account: string | null,
      sender: string | null
    ): TypedEventFilter<
      [string, string, string],
      { role: string; account: string; sender: string }
    >;

    SubmitSector(
      submitter: null,
      sector: null,
      afid: null
    ): TypedEventFilter<
      [string, string, string],
      { submitter: string; sector: string; afid: string }
    >;

    SubmitSeed(
      submitter: null,
      seed: null,
      afid: null
    ): TypedEventFilter<
      [string, string, string],
      { submitter: string; seed: string; afid: string }
    >;

    VerifySector(
      sector: null,
      seed: null,
      success: null
    ): TypedEventFilter<
      [string, string, boolean],
      { sector: string; seed: string; success: boolean }
    >;
  };

  estimateGas: {
    DEFAULT_ADMIN_ROLE(overrides?: CallOverrides): Promise<BigNumber>;

    "DEFAULT_ADMIN_ROLE()"(overrides?: CallOverrides): Promise<BigNumber>;

    REGISTER_ROLE(overrides?: CallOverrides): Promise<BigNumber>;

    "REGISTER_ROLE()"(overrides?: CallOverrides): Promise<BigNumber>;

    REWARD_ROLE(overrides?: CallOverrides): Promise<BigNumber>;

    "REWARD_ROLE()"(overrides?: CallOverrides): Promise<BigNumber>;

    SEED_ROLE(overrides?: CallOverrides): Promise<BigNumber>;

    "SEED_ROLE()"(overrides?: CallOverrides): Promise<BigNumber>;

    SUBMIT_ROLE(overrides?: CallOverrides): Promise<BigNumber>;

    "SUBMIT_ROLE()"(overrides?: CallOverrides): Promise<BigNumber>;

    VERIFY_ROLE(overrides?: CallOverrides): Promise<BigNumber>;

    "VERIFY_ROLE()"(overrides?: CallOverrides): Promise<BigNumber>;

    distributeTFC(
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "distributeTFC()"(
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    getRoleAdmin(
      role: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getRoleAdmin(bytes32)"(
      role: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    grantRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "grantRole(bytes32,address)"(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    hasRole(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "hasRole(bytes32,address)"(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    initialize(
      sectorSubmissionShare_: string,
      sectorVerificationShare_: string,
      seedSubmissionShare_: string,
      seedEvaluationShare_: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "initialize(address,address,address,address)"(
      sectorSubmissionShare_: string,
      sectorVerificationShare_: string,
      seedSubmissionShare_: string,
      seedEvaluationShare_: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    registerRNode(
      owner_: string,
      afid_: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "registerRNode(address,string)"(
      owner_: string,
      afid_: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    renounceRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "renounceRole(bytes32,address)"(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    revokeRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "revokeRole(bytes32,address)"(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    submitSector(
      rnode_: string,
      submitter_: string,
      afid_: string,
      merkleRoot_: string,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "submitSector(address,address,string,string)"(
      rnode_: string,
      submitter_: string,
      afid_: string,
      merkleRoot_: string,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    submitSeed(
      submitter_: string,
      afid_: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "submitSeed(address,string)"(
      submitter_: string,
      afid_: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    supportsInterface(
      interfaceId: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "supportsInterface(bytes4)"(
      interfaceId: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    verifySector(
      sector_: string,
      seed_: string,
      success_: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "verifySector(address,address,bool)"(
      sector_: string,
      seed_: string,
      success_: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    DEFAULT_ADMIN_ROLE(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "DEFAULT_ADMIN_ROLE()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    REGISTER_ROLE(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "REGISTER_ROLE()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    REWARD_ROLE(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "REWARD_ROLE()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    SEED_ROLE(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "SEED_ROLE()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    SUBMIT_ROLE(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "SUBMIT_ROLE()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    VERIFY_ROLE(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "VERIFY_ROLE()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    distributeTFC(
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "distributeTFC()"(
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    getRoleAdmin(
      role: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getRoleAdmin(bytes32)"(
      role: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    grantRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "grantRole(bytes32,address)"(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    hasRole(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "hasRole(bytes32,address)"(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    initialize(
      sectorSubmissionShare_: string,
      sectorVerificationShare_: string,
      seedSubmissionShare_: string,
      seedEvaluationShare_: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "initialize(address,address,address,address)"(
      sectorSubmissionShare_: string,
      sectorVerificationShare_: string,
      seedSubmissionShare_: string,
      seedEvaluationShare_: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    registerRNode(
      owner_: string,
      afid_: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "registerRNode(address,string)"(
      owner_: string,
      afid_: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    renounceRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "renounceRole(bytes32,address)"(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    revokeRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "revokeRole(bytes32,address)"(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    submitSector(
      rnode_: string,
      submitter_: string,
      afid_: string,
      merkleRoot_: string,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "submitSector(address,address,string,string)"(
      rnode_: string,
      submitter_: string,
      afid_: string,
      merkleRoot_: string,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    submitSeed(
      submitter_: string,
      afid_: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "submitSeed(address,string)"(
      submitter_: string,
      afid_: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    supportsInterface(
      interfaceId: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "supportsInterface(bytes4)"(
      interfaceId: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    verifySector(
      sector_: string,
      seed_: string,
      success_: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "verifySector(address,address,bool)"(
      sector_: string,
      seed_: string,
      success_: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
