/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface IRNodeInterface extends ethers.utils.Interface {
  functions: {
    "submitSector(string,string)": FunctionFragment;
    "verifySector(string,string)": FunctionFragment;
    "verifySector_callback(string,string,bool)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "submitSector",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "verifySector",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "verifySector_callback",
    values: [string, string, boolean]
  ): string;

  decodeFunctionResult(
    functionFragment: "submitSector",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifySector",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifySector_callback",
    data: BytesLike
  ): Result;

  events: {};
}

export class IRNode extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: IRNodeInterface;

  functions: {
    submitSector(
      _afid: string,
      _merkleRoot: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "submitSector(string,string)"(
      _afid: string,
      _merkleRoot: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    verifySector(
      sector_afid: string,
      seed_afid: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "verifySector(string,string)"(
      sector_afid: string,
      seed_afid: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    verifySector_callback(
      sector_afid: string,
      seed_afid: string,
      success: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "verifySector_callback(string,string,bool)"(
      sector_afid: string,
      seed_afid: string,
      success: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  submitSector(
    _afid: string,
    _merkleRoot: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "submitSector(string,string)"(
    _afid: string,
    _merkleRoot: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  verifySector(
    sector_afid: string,
    seed_afid: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "verifySector(string,string)"(
    sector_afid: string,
    seed_afid: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  verifySector_callback(
    sector_afid: string,
    seed_afid: string,
    success: boolean,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "verifySector_callback(string,string,bool)"(
    sector_afid: string,
    seed_afid: string,
    success: boolean,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    submitSector(
      _afid: string,
      _merkleRoot: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "submitSector(string,string)"(
      _afid: string,
      _merkleRoot: string,
      overrides?: CallOverrides
    ): Promise<void>;

    verifySector(
      sector_afid: string,
      seed_afid: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "verifySector(string,string)"(
      sector_afid: string,
      seed_afid: string,
      overrides?: CallOverrides
    ): Promise<void>;

    verifySector_callback(
      sector_afid: string,
      seed_afid: string,
      success: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    "verifySector_callback(string,string,bool)"(
      sector_afid: string,
      seed_afid: string,
      success: boolean,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    submitSector(
      _afid: string,
      _merkleRoot: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "submitSector(string,string)"(
      _afid: string,
      _merkleRoot: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    verifySector(
      sector_afid: string,
      seed_afid: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "verifySector(string,string)"(
      sector_afid: string,
      seed_afid: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    verifySector_callback(
      sector_afid: string,
      seed_afid: string,
      success: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "verifySector_callback(string,string,bool)"(
      sector_afid: string,
      seed_afid: string,
      success: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    submitSector(
      _afid: string,
      _merkleRoot: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "submitSector(string,string)"(
      _afid: string,
      _merkleRoot: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    verifySector(
      sector_afid: string,
      seed_afid: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "verifySector(string,string)"(
      sector_afid: string,
      seed_afid: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    verifySector_callback(
      sector_afid: string,
      seed_afid: string,
      success: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "verifySector_callback(string,string,bool)"(
      sector_afid: string,
      seed_afid: string,
      success: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
