/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  Contract,
  ContractTransaction,
  PayableOverrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface SectorInterface extends ethers.utils.Interface {
  functions: {
    "afid()": FunctionFragment;
    "lockedTFC()": FunctionFragment;
    "owner()": FunctionFragment;
    "turboFil()": FunctionFragment;
    "verify(bytes28,bool)": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "afid", values?: undefined): string;
  encodeFunctionData(functionFragment: "lockedTFC", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "turboFil", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "verify",
    values: [BytesLike, boolean]
  ): string;

  decodeFunctionResult(functionFragment: "afid", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "lockedTFC", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "turboFil", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "verify", data: BytesLike): Result;

  events: {
    "Verification(bytes28,bool,uint256,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "Verification"): EventFragment;
}

export class Sector extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: SectorInterface;

  functions: {
    afid(overrides?: CallOverrides): Promise<[string]>;

    "afid()"(overrides?: CallOverrides): Promise<[string]>;

    lockedTFC(overrides?: CallOverrides): Promise<[BigNumber]>;

    "lockedTFC()"(overrides?: CallOverrides): Promise<[BigNumber]>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    "owner()"(overrides?: CallOverrides): Promise<[string]>;

    turboFil(overrides?: CallOverrides): Promise<[string]>;

    "turboFil()"(overrides?: CallOverrides): Promise<[string]>;

    verify(
      seed_: BytesLike,
      success_: boolean,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "verify(bytes28,bool)"(
      seed_: BytesLike,
      success_: boolean,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  afid(overrides?: CallOverrides): Promise<string>;

  "afid()"(overrides?: CallOverrides): Promise<string>;

  lockedTFC(overrides?: CallOverrides): Promise<BigNumber>;

  "lockedTFC()"(overrides?: CallOverrides): Promise<BigNumber>;

  owner(overrides?: CallOverrides): Promise<string>;

  "owner()"(overrides?: CallOverrides): Promise<string>;

  turboFil(overrides?: CallOverrides): Promise<string>;

  "turboFil()"(overrides?: CallOverrides): Promise<string>;

  verify(
    seed_: BytesLike,
    success_: boolean,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "verify(bytes28,bool)"(
    seed_: BytesLike,
    success_: boolean,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    afid(overrides?: CallOverrides): Promise<string>;

    "afid()"(overrides?: CallOverrides): Promise<string>;

    lockedTFC(overrides?: CallOverrides): Promise<BigNumber>;

    "lockedTFC()"(overrides?: CallOverrides): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<string>;

    "owner()"(overrides?: CallOverrides): Promise<string>;

    turboFil(overrides?: CallOverrides): Promise<string>;

    "turboFil()"(overrides?: CallOverrides): Promise<string>;

    verify(
      seed_: BytesLike,
      success_: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    "verify(bytes28,bool)"(
      seed_: BytesLike,
      success_: boolean,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    Verification(
      seed: null,
      success: null,
      reward: null,
      punish: null
    ): TypedEventFilter<
      [string, boolean, BigNumber, BigNumber],
      { seed: string; success: boolean; reward: BigNumber; punish: BigNumber }
    >;
  };

  estimateGas: {
    afid(overrides?: CallOverrides): Promise<BigNumber>;

    "afid()"(overrides?: CallOverrides): Promise<BigNumber>;

    lockedTFC(overrides?: CallOverrides): Promise<BigNumber>;

    "lockedTFC()"(overrides?: CallOverrides): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    "owner()"(overrides?: CallOverrides): Promise<BigNumber>;

    turboFil(overrides?: CallOverrides): Promise<BigNumber>;

    "turboFil()"(overrides?: CallOverrides): Promise<BigNumber>;

    verify(
      seed_: BytesLike,
      success_: boolean,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "verify(bytes28,bool)"(
      seed_: BytesLike,
      success_: boolean,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    afid(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "afid()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    lockedTFC(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "lockedTFC()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "owner()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    turboFil(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "turboFil()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    verify(
      seed_: BytesLike,
      success_: boolean,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "verify(bytes28,bool)"(
      seed_: BytesLike,
      success_: boolean,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
