/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { IRNodeFactory } from "../IRNodeFactory";

export class IRNodeFactory__factory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IRNodeFactory {
    return new Contract(address, _abi, signerOrProvider) as IRNodeFactory;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "owner",
        type: "address",
      },
      {
        internalType: "string",
        name: "afid",
        type: "string",
      },
      {
        internalType: "contract ITFCShare",
        name: "_sectorSubmissionShare",
        type: "address",
      },
      {
        internalType: "contract ITFCShare",
        name: "_sectorVerificationShare",
        type: "address",
      },
    ],
    name: "produce",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];
