/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { IRNode } from "../IRNode";

export class IRNode__factory {
  static connect(address: string, signerOrProvider: Signer | Provider): IRNode {
    return new Contract(address, _abi, signerOrProvider) as IRNode;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "string",
        name: "_afid",
        type: "string",
      },
      {
        internalType: "string",
        name: "_merkleRoot",
        type: "string",
      },
    ],
    name: "submitSector",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "string",
        name: "sector_afid",
        type: "string",
      },
      {
        internalType: "string",
        name: "seed_afid",
        type: "string",
      },
    ],
    name: "verifySector",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "string",
        name: "sector_afid",
        type: "string",
      },
      {
        internalType: "string",
        name: "seed_afid",
        type: "string",
      },
      {
        internalType: "bool",
        name: "success",
        type: "bool",
      },
    ],
    name: "verifySector_callback",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];
