/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { ISector } from "../ISector";

export class ISector__factory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ISector {
    return new Contract(address, _abi, signerOrProvider) as ISector;
  }
}

const _abi = [
  {
    inputs: [],
    name: "afid",
    outputs: [
      {
        internalType: "bytes28",
        name: "",
        type: "bytes28",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "owner",
    outputs: [
      {
        internalType: "address payable",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes28",
        name: "seed_",
        type: "bytes28",
      },
      {
        internalType: "bool",
        name: "result_",
        type: "bool",
      },
    ],
    name: "verificationResult",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
];
