/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { ITFCShare } from "../ITFCShare";

export class ITFCShare__factory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ITFCShare {
    return new Contract(address, _abi, signerOrProvider) as ITFCShare;
  }
}

const _abi = [
  {
    inputs: [],
    name: "distributeTFC",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "recepient",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "mint",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];
