/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { ITurboFil } from "../ITurboFil";

export class ITurboFil__factory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ITurboFil {
    return new Contract(address, _abi, signerOrProvider) as ITurboFil;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "addr_",
        type: "address",
      },
    ],
    name: "hasVerifyRole",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];
